name: thoughts
description: A game

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flame: ^0.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter
